# Generated by Django 3.2.9 on 2022-05-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='source_pk',
            field=models.CharField(max_length=255, null=True, verbose_name='Первичный ключ из источника'),
        ),
    ]
