# Generated by Django 3.2.9 on 2021-12-25 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Уровень')),
                ('enable', models.BooleanField(default=True, verbose_name='Включен')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
        ),
    ]
