# Generated by Django 3.2.9 on 2021-12-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('f', 'Фильтр')], default='f', max_length=1, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
