# Generated by Django 3.2.9 on 2021-12-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_module_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('f', 'Фильтр'), ('s', 'Фичи')], max_length=1, verbose_name='Тип'),
        ),
    ]
