# Generated by Django 3.2.9 on 2022-04-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='for_all_users',
            field=models.BooleanField(default=False),
        ),
    ]
