# Generated by Django 3.2.9 on 2022-04-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_module_for_all_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='for_all_users',
            new_name='public',
        ),
    ]
