# Generated by Django 3.2.9 on 2021-12-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Уровень'),
            preserve_default=False,
        ),
    ]
