# Generated by Django 3.2.9 on 2021-12-21 15:45

import apps.helpers.models
import apps.subscription.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20211221_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscription',
            field=models.OneToOneField(default=apps.subscription.models.Subscription.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='subscription.subscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=apps.helpers.models.PriceField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Цена'),
        ),
    ]
