# Generated by Django 3.2.9 on 2022-01-23 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Город')),
                ('remote', models.BooleanField(default=False, verbose_name='Удаленная работа')),
                ('tags', models.ManyToManyField(related_name='vacancies', to='resume.Tag', verbose_name='Навыки')),
            ],
        ),
    ]
