# Generated by Django 3.2.9 on 2021-12-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_basefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefilter',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Включен'),
        ),
    ]
