# Generated by Django 3.2.9 on 2021-12-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_basefilter_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='Удаленная работа'),
        ),
    ]
