# Generated by Django 3.2.9 on 2021-12-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_auto_20211225_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseFilter',
        ),
    ]
