# Generated by Django 3.2.9 on 2022-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Работодатель', 'Employer'), ('Работник', 'Worker')], default='Работник', max_length=16, verbose_name='Роль'),
        ),
    ]
