# Generated by Django 3.2.9 on 2022-05-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Работодатель'), ('worker', 'Работник')], default='worker', max_length=16, verbose_name='Роль'),
        ),
    ]
