# Generated by Django 3.2.9 on 2021-12-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('dflt', 'Обычный пользователь'), ('subs', 'Подписчик'), ('adve', 'Рекламодатель')], default='dflt', max_length=4, verbose_name='Роль'),
        ),
    ]
