# Generated by Django 3.2.9 on 2022-05-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enemy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enemy.enemy')),
            ],
            options={
                'abstract': False,
            },
            bases=('enemy.enemy',),
        ),
    ]
