# Generated by Django 3.2.9 on 2021-12-21 16:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Промокод')),
                ('max_activations', models.PositiveSmallIntegerField(default=1, verbose_name='Максимум активаций')),
                ('count_activations', models.PositiveSmallIntegerField(default=0, verbose_name='Всего активаций')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promocode.promocode')),
            ],
            options={
                'verbose_name': 'Активация',
                'verbose_name_plural': 'Активации',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
