# Generated by Django 3.2.9 on 2021-12-20 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promocode', '0002_promocode_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promocode.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активация',
                'verbose_name_plural': 'Активации',
                'unique_together': {('user', 'promocode')},
            },
        ),
    ]
