# Generated by Django 3.2.9 on 2021-12-20 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0003_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
    ]
