# Generated by Django 3.2.9 on 2021-12-20 14:12

from decimal import Decimal
import django.core.validators
from django.db import migrations
import helpers.models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0005_alter_promocode_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='price',
            field=helpers.models.PriceField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Цена'),
        ),
    ]
